# For more information: https://laravel.com/docs/sail
version: '3'
services:
  calcify-backend:
    image: abhishekpaul2008/calcify-backend
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${APP_PORT:-4000}:3300'
    env_file:
      - .env # path to your .env file
    environment:
      DB_HOST: 3.111.146.203
      DB_PASSWORD: myPassword
      TZ: Asia/Kolkata
    # network_mode: bridge
    networks:
      - default
      - nginx-proxy-manager_default
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3300']
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 60s
    links:
      - chrome
    # depends_on:
      # - redis
  
  chrome:
    image: zenika/alpine-chrome:latest
    command: [chromium-browser, "--headless", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - "9222:9222"
    restart: unless-stopped

#   redis:
#     image: 'redis:alpine'
#     ports:
#       - '${FORWARD_REDIS_PORT:-6379}:6379'
#     volumes:
#       - 'sailredis:/data'
#     networks:
#       - sail
#     healthcheck:
#       test: ['CMD', 'redis-cli', 'ping']

networks:
  nginx-proxy-manager_default:
    external: true

# volumes:
#   sailredis:
#     driver: local
